FROM golang:1.9.4-stretch

# RUN apk update && apk upgrade && \
#     apk add --no-cache bash git openssh

RUN apt-get update -y && apt-get upgrade -y 

RUN git clone https://github.com/edenhill/librdkafka.git && \
  cd librdkafka && \
  ./configure --prefix /usr && \
  make && \
  make install && \
  cd ..

WORKDIR /go/src/consumerpg
COPY . .

RUN go-wrapper download
RUN go-wrapper install

CMD ["go-wrapper", "run"]
